import { Injectable } from '@angular/core';
import { Foods } from '../../shared/models/food';
@Injectable({
  providedIn: 'root'
})
export class FoodService {

  constructor() { }

  getFoodById(id:number): Foods{
    return this.getAll().find(food => food.id == id)!;
  }

  getAll():Foods[]{
    return [
      {
        id: 1,
        name: 'Black Current',
        price: 50,
        cookTime: '30-35 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/BlackCurrent.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 2,
        name: 'Black Forest',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/BlackForest.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 3,
        name: 'Blue Berry',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/Blueberry.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 4,
        name: 'Cherry Topped Rainbow',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/cherryRainbow.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 5,
        name: 'Chocolate Tuffle',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/ChocolateTuffle.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 6,
        name: 'Chocolasious',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/chocoSofa.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 7,
        name: 'Rainbow Dipped',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/colourDipped.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 8,
        name: 'Chocolate Donnet',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/Donnet.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 9,
        name: 'Rainbow Tuffed',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/FunnyTuffed.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 10,
        name: 'Heart RedVelvet',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/heart.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 11,
        name: 'Toy RedVelvet',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/Redcar.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 12,
        name: 'Tiramisu Cake',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/Tiramisu1.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 13,
        name: 'Creamy Tiramisu',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/tiramisu2.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 14,
        name: 'White Forest',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/Vanilla.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 15,
        name: '50-50',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/vanillaChoco.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      {
        id: 16,
        name: 'Vanilla Fruity',
        price: 40,
        cookTime: '15-20 min',
        favorite: true,
        origins: ['Belgium','France'],
        star: 3.3,
        imageUrl: '/assets/VanillaFruity.jpeg',
        tags: ['Rainbow', 'Delicious'],
      },
      
    ]
  }
}

